name: github pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      - run: mdbook build

      - name: Build and push docker image
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
        run: |
          echo 'Docker login'
          docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_SECRET
          echo 'Running build...'
          docker build --no-cache ./book -t delsynn/mdbook:latest
          echo 'Pushing image...'
          docker push delsynn/mdbook:latest
          echo 'Done !'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book